<tr class="form-field">
    <th scope="row" valign="top">
        <label for="taxonomy_image"><?php _e('Image'); ?></label>
    </th>
    <td>
        <input type="text" name="taxonomy_image" id="taxonomy_image"
               value="<?php echo $img = get_option('taxonomy_image_' . $taxonomy->term_id) ?>"/>

			<?php if ($img) { ?>
        <img src="<?php echo $img?>" alt="Taxonomy image"/>
			<?php }?>
    </td>
</tr>