<script type="text/javascript">
    jQuery(document).ready(function () {
        jQuery("#taxonomy_image").click(function () {
            tb_show("", "media-upload.php?type=image&amp;TB_iframe=true");
            return false;
        });
        window.send_to_editor = function (html) {
            imgurl = jQuery("img", html).attr("src");
            jQuery("#taxonomy_image").val(imgurl);
            tb_remove();
        }
    });
</script>